const socket=io(), $=id=>document.getElementById(id); let currentRoom='',pc,dc,stream,isInitiator=false,tttState=Array(9).fill(''),tttTurn='X',myMark='X';
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')} window.show=show;
$('create').onclick=()=>socket.emit('create-room',{name:$('nick').value,pin:$('pin').value},r=>{if(r.ok){currentRoom=r.id;isInitiator=true;$('roomInfo').textContent='Room '+r.id+' — share this code with your partner';enterChat();setupPeer(true)}});
$('join').onclick=()=>socket.emit('join-room',{id:$('roomCode').value,name:$('nick').value,pin:$('pin').value},r=>{if(!r.ok)return $('roomInfo').textContent=r.error;currentRoom=r.id;isInitiator=false;enterChat();setupPeer(false)});
function enterChat(){show('chat');$('chatTitle').textContent=currentRoom.startsWith('R-')?'Random Connect':'Room '+currentRoom;$('status').textContent='Waiting for peer…'}
socket.on('peer-ready',()=>{if(isInitiator&&pc)makeOffer()}); socket.on('peer-left',()=>{$('status').textContent='Peer left';if(dc)dc.close()});
async function setupPeer(init){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.onicecandidate=e=>e.candidate&&socket.emit('signal',{toRoom:currentRoom,data:{candidate:e.candidate}});pc.ontrack=e=>$('remote').srcObject=e.streams[0];pc.onconnectionstatechange=()=>{$('status').textContent=pc.connectionState};if(init){bindDC(pc.createDataChannel('twovya'))}else pc.ondatachannel=e=>bindDC(e.channel)}
function bindDC(c){dc=c;dc.onopen=()=>{$('status').textContent='Private peer connection ready'};dc.onmessage=e=>{let d=JSON.parse(e.data);if(d.type==='msg')bubble(d.text,false);if(d.type==='ttt'){tttState=d.board;tttTurn=d.turn;renderTTT()}}}
async function makeOffer(){const o=await pc.createOffer();await pc.setLocalDescription(o);socket.emit('signal',{toRoom:currentRoom,data:{sdp:pc.localDescription}})}
socket.on('signal',async({data})=>{if(!pc)await setupPeer(false);if(data.sdp){await pc.setRemoteDescription(data.sdp);if(data.sdp.type==='offer'){const a=await pc.createAnswer();await pc.setLocalDescription(a);socket.emit('signal',{toRoom:currentRoom,data:{sdp:pc.localDescription}})}}else if(data.candidate)try{await pc.addIceCandidate(data.candidate)}catch(e){}});
$('send').onclick=send;$('msg').onkeydown=e=>e.key==='Enter'&&send();function send(){let t=$('msg').value.trim();if(!t)return;if(!dc||dc.readyState!=='open')return alert('Peer connection is not ready yet.');dc.send(JSON.stringify({type:'msg',text:t}));bubble(t,true);$('msg').value=''}function bubble(t,m){let d=document.createElement('div');d.className='bubble '+(m?'mine':'');d.textContent=t;$('messages').appendChild(d);$('messages').scrollTop=1e9}
$('findRandom').onclick=()=>{socket.emit('random-find',{name:$('rnick').value});$('randomStatus').textContent='Looking for someone…'};socket.on('random-wait',()=>$('randomStatus').textContent='Waiting for another online person…');socket.on('random-match',async r=>{currentRoom=r.id;isInitiator=r.initiator;enterChat();await setupPeer(isInitiator);if(isInitiator)setTimeout(makeOffer,250)});$('nextRandom').onclick=()=>socket.emit('random-next');
$('callBtn').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true,video:true});$('local').srcObject=stream;stream.getTracks().forEach(t=>pc.addTrack(t,stream));$('call').classList.remove('hidden');if(isInitiator)await makeOffer()}catch(e){alert('Camera/microphone permission is required for calls.')}};$('hang').onclick=()=>{stream?.getTracks().forEach(t=>t.stop());$('call').classList.add('hidden')};$('mute').onclick=()=>stream?.getAudioTracks().forEach(t=>t.enabled=!t.enabled);$('cam').onclick=()=>stream?.getVideoTracks().forEach(t=>t.enabled=!t.enabled);
function startTTT(){show(currentRoom?'chat':'games');$('ttt').classList.remove('hidden');renderTTT()}window.startTTT=startTTT;function renderTTT(){$('ttt').innerHTML='';tttState.forEach((v,i)=>{let b=document.createElement('button');b.textContent=v;b.onclick=()=>{if(v||tttTurn!==myMark)return;tttState[i]=myMark;tttTurn=myMark==='X'?'O':'X';renderTTT();dc?.readyState==='open'&&dc.send(JSON.stringify({type:'ttt',board:tttState,turn:tttTurn}))};$('ttt').appendChild(b)})}
const funs=['Truth: What is something you have never told me?','Dare: Send your funniest selfie 😄','Would you rather travel to the past or future?','Describe your mood using only 3 emojis.','Rapid fire: Tea or coffee? Night or morning? Call or text?','Give the other person a funny 30-second challenge.'];function fun(){$('funCard').textContent=funs[Math.floor(Math.random()*funs.length)]}window.fun=fun;
let board2048;function start2048(){board2048=[2,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0];render2048()}window.start2048=start2048;function render2048(){let a=$('gameArea');a.innerHTML='<p>2048 starter board — swipe controls will be expanded in the next game-engine build.</p><div class="tile2048">'+board2048.map(x=>`<div>${x||''}</div>`).join('')+'</div>'}
let deferred;$('install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null}else alert('Browser menu → Add to Home screen / Install app')};addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
